### PR TITLE
New functions to the library

### PR DESCRIPTION
**Pull request by Gianfranco97**
## Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Conventional Commit](http://conventionalcommits.org/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue # N/A

## What is the new behavior?

in this PR:
- add functions:
  - killSession 
  - getMyProfiles 
  - getActiveProfile 
  - changeActiveProfile 
  - getMyEntities 
  - getActiveEntities 
  - changeActiveEntities 
  - getFullSession 
  - getAnItem 
  - getAllItems 
  - getSubItems 
  - addItem 
  - addItems 
  - lostPassword 
  - updateItem 
  - updateItems 
  - deleteItem 
  - deleteItems 
- add code examples with promises and async/await
- validate code with eslint 
- add unit tests for all functions
## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

### CODE REVIEW

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 Could you rebase your branch to resolve the conflicts?

Thanks

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Comment by Gianfranco97** [comment]
I already resolved the conflicts

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Pull request merged**
